### PR TITLE
upgrade angular to 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by hermanfransen**
Thanks for this very useful repo, to contribute I upgraded it to rc1.

### CODE REVIEW

**Comment by schempy** [comment]
@hermanfransen Thanks for contributing!

I'm getting compiling errors running `npm run build` and `npm run start`. Could you take a look? Tested using node v4.0.0 and v5.7.1

**Comment by hermanfransen** [comment]
Do you have also the second commit? "solved typescript compiler error messages" besides "upgrade angular2 from 2.0.0-beta.13 to 2.0.0-rc.1".....

**Comment by hermanfransen** [comment]
See also `readme.md`  
Did you do a `typings install` ?  
Installing `es6-shim` as typings makes these compile error messages disappear

**Comment by hermanfransen** [comment]
Do a `typings install`, this will install `es6-shim`  

These typings make the typescript compile errors disappear  

See also changed `readme.md`

**Comment by schempy** [comment]
@hermanfransen That did it! Stupid mistake on my part. Thanks again!

**Pull request merged**
